const AUTH_REQUEST='AUTH_REQUEST'
const AUTH_SUCCESS='AUTH_SUCCESS'
const AUTH_FAIL='AUTH_FAIL'
const AUTH_REFRESH_REQUEST='AUTH_REFRESH_REQUEST'
const AUTH_REFRESH_SUCCESS='AUTH_REFRESH_SUCCESS'
const AUTH_REFRESH_FAIL='AUTH_REFRESH_FAIL'



export {AUTH_SUCCESS,AUTH_REQUEST,AUTH_FAIL,AUTH_REFRESH_SUCCESS,AUTH_REFRESH_REQUEST,AUTH_REFRESH_FAIL}