const USER_BET_REQUEST='USER_BET_REQUEST'
const USER_BET_SUCCESS='USER_BET_SUCCESS'
const USER_BET_FAIL='USER_BET_FAIL'
const USER_CASH_OUT_REQUEST='USER_CASH_OUT_REQUEST'
const USER_CASH_OUT_SUCCESS='USER_CASH_OUT_SUCCESS'
const USER_CASH_OUT_FAIL='USER_CASH_OUT_FAI'


export {
    USER_BET_SUCCESS,
    USER_BET_REQUEST,
    USER_BET_FAIL,
    USER_CASH_OUT_SUCCESS,
    USER_CASH_OUT_REQUEST,
    USER_CASH_OUT_FAIL
}